cloudinstall/multi_install.py
test/test_multi_new_maas.py

quote password arg to createsuperuser.
add tests
some refactoring to make tests work

Fix #322. Includes tests.

---

cloudinstall/single_install.py
cloudinstall/utils.py

- use lxc-info to get container's ip instead of parsing dnsmasq lease files directly. avoids issue where sometimes initial run found spurious IP.
- use Popen directly in container_run to enable us to get stderr separately
- improve cloud_init_finished to only ignore real errors up to 20 times, then raise them.
This avoids having us spin forever waiting for the cloud-init JSON, when we can't even reach the container due to e.g. lxc network misconfiguration.

More robust container_ip and container_run with better error handling

---

tools/vm-batch

Fixes #350
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/354)

Add option to specify vm image size

---

bin/configure-landscape

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/358)

make use of saved config object in configuring landscape

---

bin/configure-landscape
bin/openstack-install
bin/openstack-juju
cloudinstall/charms/controller.py
cloudinstall/charms/glance_simplestreams_sync.py
cloudinstall/charms/quantum.py
cloudinstall/config.py
cloudinstall/core.py
cloudinstall/multi_install.py
cloudinstall/single_install.py
cloudinstall/utils.py
docs/single-installer.guide.rst
test/test_config.py
tools/openstack-uninstall

Isolates juju files from the rest of the installer

Keep juju files in a subdirectory of .cloud-install

---

cloudinstall/maas/__init__.py

1.8 is temporarily persnickety and we might as well be nice

avoid generating technically incorrect api urls for maas.

---

cloudinstall/ui/dialog.py

remove noisy log mesages

---

bin/openstack-install
cloudinstall/core.py
cloudinstall/gui.py

currently only works for single installer due to hardcoded path in get_log_text

Tail juju logs

---

share/templates/charmconf.yaml

Added conditional to cover the case of ceph or not ceph to cinder config.

Added storage_backend == 'ceph' to cinder conf.

---

cloudinstall/core.py

Fix for issue #430. Changed self.nodes = None to self.nodes = [].

Fix for issue #430. Changed self.nodes = None to self.nodes = []

---

cloudinstall/charms/cinder_ceph.py

Corrected module name in getLogger.

Changed 'cinder-ceph' to 'cinder_ceph'

---

cloudinstall/charms/__init__.py
cloudinstall/charms/ceph_osd.py
cloudinstall/charms/ceph_radosgw.py
cloudinstall/charms/compute.py
cloudinstall/charms/controller.py
cloudinstall/charms/glance.py
cloudinstall/charms/glance_simplestreams_sync.py
cloudinstall/charms/horizon.py
cloudinstall/charms/keystone.py
cloudinstall/charms/mysql.py
cloudinstall/charms/neutron_api.py
cloudinstall/charms/neutron_openvswitch.py
cloudinstall/charms/quantum.py
cloudinstall/charms/rabbitmq.py
cloudinstall/charms/swift.py
cloudinstall/charms/swift_proxy.py
cloudinstall/multi_install.py
cloudinstall/placement/controller.py
cloudinstall/placement/ui.py
cloudinstall/single_install.py
cloudinstall/state.py
test/test_placement_controller.py
test/test_placement_ui.py

CharmState class added to set REQUIRED, OPTIONAL along with
acting up charms depends/conflicts definitions

Support CharmState and depends/conflicts

---

cloudinstall/single_install.py

Just so it doesn't look like it's taking forever to create an LXC, which should be fast (and it is, we just do a lot in the 'creating container' task)

add extra task to be clearer about where time is going

---

cloudinstall/utils.py

include stderr in results of get_command_output

---

cloudinstall/charms/controller.py
cloudinstall/netutils.py
cloudinstall/single_install.py
share/templates/lxc-net
share/templates/nova-controller-setup.sh
test/test_netutils.py
tools/openstack-uninstall

Generate unique subnets so multiple users can install concurrently on one system

unique single installer routes for multiple installs on one system

---

cloudinstall/multi_install.py
test/test_multi_install.py

NOTE: untested, I do not have access to hardware to test multi-install at the moment.

Add bootstrap node IP to no-proxy env after bootstrap succeeds.

---

cloudinstall/charms/ceilometer.py
cloudinstall/charms/ceilometer_agent.py
cloudinstall/charms/cinder_ceph.py

cinder-ceph requires both cinder and ceph (but not the other direction)
and ceilometer and ceilometer-agent require each other.

Add some missing deps

---

cloudinstall/charms/ceilometer.py
cloudinstall/charms/ceilometer_agent.py

Appended 'mongodb' to depends attribute for ceilometer

---

cloudinstall/placement/ui/__init__.py
cloudinstall/placement/ui/filter_box.py
cloudinstall/placement/ui/machine_chooser.py
cloudinstall/placement/ui/machine_widget.py
cloudinstall/placement/ui/machines_list.py
cloudinstall/placement/ui/service_chooser.py
cloudinstall/placement/ui/service_widget.py
cloudinstall/placement/ui/services_list.py
test/test_placement_ui.py

Refactoring: move placement UI classes to separate files.

---

cloudinstall/multi_install.py

Attempt to get IP of hostname listed in juju status because some code accesses the bootstrap node using IP instead of hostname, and having the hostname in no-proxy does us no good then.

Resolve hostname for bootstrap node in no-proxy. Fixes #520

---

cloudinstall/placement/controller.py

Fixes issue with deploying swift to single

fix default constraints: do not treat empty dict as None

---

cloudinstall/utils.py

Just a little something to aid in debugging

log instances where options are overridden during dict updates

---

cloudinstall/config.py
cloudinstall/core.py
cloudinstall/placement/controller.py
cloudinstall/placement/ui/__init__.py
test/test_placement_controller.py

First part of the config refactoring based on http://git.io/vekuk

replace placements in separate config file

---

cloudinstall/charms/jujugui.py

Incremented charm_rev attribute of CharmJujuGui to 24.

Increment juju-gui rev to latest.

---

cloudinstall/gui.py

Added 'https' instead of http.

Corrected openstack-dashboard url.

---

cloudinstall/charms/rabbitmq.py

Incremented charm_rev attribute of CharmRabbitMQ to 29.

Increment rabbitmq-server rev to latest.

---

cloudinstall/charms/compute.py

Incremented nova-comptue rev to 17

Increment nova-compute rev to latest

---

cloudinstall/charms/cinder.py

Incremented cinder rev to latest

---

cloudinstall/placement/ui/machine_chooser.py

Changed "show_assignments" to "show_placements" in machine_chooser.py

Fix for #556

---

bin/openstack-install
cloudinstall/utils.py
share/templates/charmconf.yaml
test/test_utils.py

Add charm config support for deploying charms via OpenStack master

---

share/templates/charmconf.yaml

remove unnecessary options dict

---

share/templates/charmconf.yaml

Add the rest of neutron's repos to neutron charm configs

---

cloudinstall/install.py
requirements.txt
test/test_charm_controller.py

Didn't make much sense to have entering the password as the first dialog,
reversed it with the install path selection.
Also was a recent upload to nilsimsa on pypi which fails to install properly,
bumped version back to last successful install.

Switch password and install selection prompts

---

cloudinstall/charms/mongodb.py

Bumped mongodb rev to latest

---

cloudinstall/charms/compute.py

Incremented nova-compute rev to 24

Bumped nova-compute rev to latest

---

cloudinstall/charms/cinder.py

Bumped cinder rev to latest

---

cloudinstall/charms/jujugui.py

Incremented juju-gui rev to 27

Bumped juju-gui rev to latest

---

cloudinstall/charms/glance.py

Bumped glance rev to latest

---

cloudinstall/install.py

Fix error during headless mode calling extra argument in do_install

---

cloudinstall/charms/__init__.py

Do not define machine spec in local_deploy if subordinate charm

---

cloudinstall/charms/__init__.py
cloudinstall/charms/ceilometer.py
cloudinstall/charms/ceilometer_agent.py
cloudinstall/charms/ceph.py
cloudinstall/charms/ceph_osd.py
cloudinstall/charms/ceph_radosgw.py
cloudinstall/charms/cinder.py
cloudinstall/charms/cinder_ceph.py
cloudinstall/charms/compute.py
cloudinstall/charms/controller.py
cloudinstall/charms/glance.py
cloudinstall/charms/heat.py
cloudinstall/charms/horizon.py
cloudinstall/charms/keystone.py
cloudinstall/charms/neutron_api.py
cloudinstall/charms/neutron_openvswitch.py
cloudinstall/charms/quantum.py
cloudinstall/charms/rabbitmq.py
cloudinstall/charms/swift.py
cloudinstall/charms/swift_proxy.py

Easier to extend this property for future OpenStack plugins who
take part in the charmers /next branch.

Make have_nextbranch part of charms class variable

---

cloudinstall/juju.py

RequestTimeout was added in the version of macumba that we imported with e2560ce68a3ede59ec4c1b4218259ae9f63b1fd0

Handle timeouts from juju client status() by retrying up to 5 times

---

bin/openstack-install
cloudinstall/multi_install.py
cloudinstall/single_install.py
cloudinstall/utils.py
share/templates/juju-env/maas.yaml
share/templates/juju-env/single.yaml
test/test_utils.py

Now that we can support locally deploying charms to different series, this code change makes sense to add.

Series config

---

bin/openstack-install
cloudinstall/charms/__init__.py
test/test_charms.py

Adds support for nclxd using latest default-series work. 
Ref: #573

Support for nclxd

---

cloudinstall/ev.py

Makes -i work again.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/605)

Exceptions on non-ui threads set an Event to ensure the UI dies.

---

cloudinstall/single_install.py
cloudinstall/task.py
cloudinstall/utils.py

Adds an extra step "Initializing container" to differentiate container creation from cloud-init running.
Displays up to ten lines of relevant info for each step. Mostly it's apt messages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/606)

Better feedback single

---

share/templates/userdata.yaml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/607)

fixes #403

---

cloudinstall/utils.py

Nothing major may shave off install wait time for slower ssh connections.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/614)

Feature ssh multiplex

---

bin/openstack-install
cloudinstall/single_install.py
docs/openstack-config.md
docs/single-installer.guide.rst
man/en/openstack-config.5
share/templates/userdata.yaml
test/test_config.py

This will support instances where people are running experimental
and/or with a proxy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/617)

Add all ppa's into userdata.yaml

---

share/templates/nova-controller-setup.sh

Fixes #622.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/626)

Ensure running nova-controller-setup script multiple times is safe.

---

cloudinstall/charms/__init__.py

Tweak logic so when --use-nclxd and --next-charms are both specified, we
download the next charms into a local repo with the right series in the
path, which lets the charms know it's OK to support nclxd.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/630)

Support --use-nclxd and --next-charms together

---

cloudinstall/consoleui.py
cloudinstall/install.py
cloudinstall/utils.py
test/test_config.py
test/test_utils.py

Cleanup configuration merging using python's builtin ChainMap collection
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/645)

Patch chainmap config

---

Makefile

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/649)

link external debian stuff directly into debian/

---

share/templates/userdata.yaml

There is no repo at http://ppa.launchpad.net/cloud-installer/testing/ubuntu $RELEASE main
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/671)

Fix error at package install stage

---

cloudinstall/placement/ui/__init__.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/674)

we should use title case in buttons

---

cloudinstall/placement/controller.py

Also fixes spacing issue on warning.
Fixes #675 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/677)

Avoid using placeholders in auto-place

---

bin/openstack-install
cloudinstall/charms/ceph.py
cloudinstall/charms/ceph_osd.py
cloudinstall/charms/ceph_radosgw.py
cloudinstall/charms/cinder.py
cloudinstall/charms/cinder_ceph.py
cloudinstall/charms/compute.py
cloudinstall/charms/controller.py
cloudinstall/charms/glance.py
cloudinstall/charms/heat.py
cloudinstall/charms/horizon.py
cloudinstall/charms/jujugui.py
cloudinstall/charms/keystone.py
cloudinstall/charms/mongodb.py
cloudinstall/charms/mysql.py
cloudinstall/charms/neutron.py
cloudinstall/charms/neutron_api.py
cloudinstall/charms/neutron_openvswitch.py
cloudinstall/charms/ntp.py
cloudinstall/charms/rabbitmq.py
cloudinstall/charms/swift.py
cloudinstall/charms/swift_proxy.py
cloudinstall/controllers/installbase.py

Bumps charm revs to latest, and adds liberty to list of available releases.
This works in testing as long as you also specify --next-charms, as liberty isn't supported in the currently shipping charms.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/689)

add liberty

---

cloudinstall/controllers/install/single.py
share/templates/userdata.yaml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/698)

Install bzr in in single container if next_charms is set

---

cloudinstall/alarms.py
cloudinstall/controllers/installbase.py
cloudinstall/core.py
cloudinstall/ev.py
cloudinstall/task.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/701)

Remove alarms as they are fired, and avoid logspew

---

cloudinstall/charms/__init__.py
cloudinstall/core.py
cloudinstall/gui.py

Also improve logging to track relations.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/706)

Display status of post-processing phases

---

cloudinstall/config.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/710)

Check for existence of config file before backup

---

bin/openstack-install

Fixes #700
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/711)

Add ability to force uninstall

---

cloudinstall/utils.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/714)

Re-set permissions during cleanup

---

cloudinstall/charms/__init__.py

Fixes #715
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/716)

Quote openstack export variables

---

cloudinstall/charms/glance_simplestreams_sync.py

Fixes #702
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/743)

Use charmstore glance-s-s

---

cloudinstall/controllers/install/single.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/750)

Add TRACE_JUJU env var sets juju logging to trace

---

cloudinstall/core.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/760)

Juju has fixed the unique hostnames for containers

---

cloudinstall/async.py
cloudinstall/charms/__init__.py
cloudinstall/controllers/install/single.py
cloudinstall/core.py
cloudinstall/task.py
cloudinstall/ui/views/machinewait.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/757)

Rework background tasks to run in a single thread at any given time

---

cloudinstall/utils.py
test/files/openstack-admin-rc-extended
test/test_openstack_rc.py

Fixes #764
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/765)

Sanitize any quotes found in the rc files

---

cloudinstall/charms/ceilometer.py
cloudinstall/charms/ceilometer_agent.py
cloudinstall/charms/ceph.py
cloudinstall/charms/ceph_osd.py
cloudinstall/charms/ceph_radosgw.py
cloudinstall/charms/cinder.py
cloudinstall/charms/cinder_ceph.py
cloudinstall/charms/compute.py
cloudinstall/charms/controller.py
cloudinstall/charms/glance.py
cloudinstall/charms/heat.py
cloudinstall/charms/horizon.py
cloudinstall/charms/jujugui.py
cloudinstall/charms/keystone.py
cloudinstall/charms/mongodb.py
cloudinstall/charms/mysql.py
cloudinstall/charms/neutron.py
cloudinstall/charms/neutron_api.py
cloudinstall/charms/neutron_openvswitch.py
cloudinstall/charms/ntp.py
cloudinstall/charms/rabbitmq.py
cloudinstall/charms/swift.py
cloudinstall/charms/swift_proxy.py

Fixes #766
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/768)

update charm revs to support Liberty in full

---

cloudinstall/gui.py
cloudinstall/ui/views/services.py

also removes some unused code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/777)

status: Fix display of jujugui charm

---

bin/openstack-install
cloudinstall/charms/neutron.py
cloudinstall/controllers/install/landscape.py
cloudinstall/controllers/install/multi.py
cloudinstall/controllers/install/single.py
cloudinstall/utils.py
debian/control

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/767)

Check's entropy from ubuntu.com

---

cloudinstall/utils.py
share/templates/charmconf.yaml

Creating this PR so we can test and discuss any changes/challenges
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/763)

add support for --series wily

---

bin/openstack-install

It's time..
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/782)

make liberty default

---

cloudinstall/controllers/installbase.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/804)

Add callback so 'r' refreshes instead of crashing

---

tools/fast-run-single-status

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/805)

tools: fix fast-run-single-status for lxc+lxd

---

cloudinstall/controllers/install/single.py

containers will not necessarily have /dev/console configured as
expected.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/835)

Ignore some cloud-init errors if lxd is toplevel

---

cloudinstall/api/container.py
cloudinstall/controllers/install/single.py

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/836)

Fix cloudinit errs

---

bin/openstack-install
cloudinstall/config.py

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/854)

add mitaka options

---

bin/openstack-install
cloudinstall/utils.py

Fixes #860 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/881)

don't assume that there's a group with the same name as the installing user

---

cloudinstall/controllers/install/multi.py
share/templates/juju-env/maas.yaml

Needs testing with a live maas server - I wasn't able to test it due to issues with our MAAS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/939)

Improve handling of ports entered with maas URL
