- debian/control
- share/templates/userdata.yaml
we do end up needing juju-local-kvm, and if we don't install it here, the bootstrap will fail later
> fix deps for openstack-single and actually install it in the container

- cloudinstall/single_install.py
Because of the potential for interfaces to be temporarily invisible, we will just treat a container with no IP as always a retry-able error.
If we see issues in the future where containers are losing networking, causing the installer to wait forever, we might consider keeping a counter to retry only N times, but for now that doesn't seem necessary.
And this code will at least let us know that that's what's happening if that does end up being a problem.
> just always retry after container IP errors

- cloudinstall/placement/controller.py
- test/test_placement_controller.py
Only select READY machines for default placement.
Adds tests.
Verified with the nodes list from #342 that earlier code was selecting a BROKEN node. This code does not select that node.
> ensure that gen_defaults filters out non-ready machines, fixes #342

- cloudinstall/utils.py
In a lot of environments there is no specific user group.
Limit the access to user only, default ssh.
(Closes: LP#1413249)
> ssh_genkey: don't assume that $USER == $GROUP

- bin/openstack-install
- bin/openstack-status
- cloudinstall/config.py
- cloudinstall/utils.py
- test/files/good_config.yaml
- test/test_config.py
Provides better logic for handling pulling config items from presaved configs, a config file passed into via `--config` and handles updating config object with items passed in via cli
> Patch populate config

- cloudinstall/charms/controller.py
- share/templates/nova-controller-setup.sh
With `multi` install path we'll require that 2 NICS be available and let the neutron charm configure itself automatically.
> only create neutron network automatically if Single install

- tools/openstack-uninstall
this avoids being unnecessarily specific and deletes any route for the given prefix, assuming we set it up.
Otherwise, occasionally an install can get wedged because the new config has an IP that doesn't match the ip of the route we added previously.
> remove unnecessary ip route del args

- cloudinstall/single_install.py
When debugging the status screen, sometimes it's convenient to bind in the source dir into the container to make tweaks and re-run.
added as a hidden env var because it is just for development
> add EXTRA_BIND_DIRS to bind additional directories into the container

- bin/openstack-install
- cloudinstall/placement/controller.py
- test/test_placement_controller.py
Ensure that storage_backend is always set, and add checks for cases where it might not be.
Also rework storage service filtering to take into account new charms and the case where no backend is selected.
Finally, fix tests that do not have a config set up by argparser.
> Fix storage backend

- cloudinstall/install.py
- cloudinstall/single_install.py
Changes from the addition of headless mode ended up hiding exceptions and breaking the error dialog box, resulting in timers running forever with no error indicator.
The issue is that calling self.loop.exit() ends up raising urwid.ExitMainLoop, which gets caught specifically in the urwid main loop and thus does not make it to our global exception handler, which is what generates the error dialog.
This fixes this in two ways:
1. It changes the headless code to catch and log all top level exceptions, and handles exiting cleanly there. This means that code in the Install classes does not have to worry about headless vs. regular, and can just raise exceptions and trust that whatever main loop is being used will do the right thing.
2. It changes a bunch of places in single_install where we …
> Bring back error dialogs

- Makefile
Currently doing 'make type=single' still installs all packages. This is inconvenient when multi's deps are not desired (like maas).
This fix makes it so that type=single only installs single.
> Makefile target tweak to permit installing only single-install package if desired

- cloudinstall/single_install.py
1. moves check for upstream deb file to before any real time gets spent.
2. ssh_genkey doesn't need to have its exception rewrapped and printed twice 
3. remove some comments that don't say any more than the code they're next to
> Check upstream deb sooner

- bin/openstack-install
- bin/openstack-status
- cloudinstall/single_install.py
- docs/single-installer.guide.rst
- tools/openstack-uninstall
Simple support for different user accounts to have their own single-install container: just adds the username to the container name.
> Per-user container names

- cloudinstall/install.py
Bare exceptions in headless mode (outside of do_install) are ignored, so log and exit with rc=1 instead.
> Ensure that missing install_type error gets printed

- bin/openstack-install
uninstall and kill-cloud should use the same code.
there were two options:
1. move everything into python and remove the script - this involved adding multi-install removal code to the python stuff
2. just make killcloud-* use the script like uninstall does.
I chose 2 because it's faster and the multi-install removal code in the shell script has been tested.
> remove duplicate code for killcloud

- cloudinstall/placement/controller.py
fixes #343
the strategy suggested in #343's comments was good but we never found time to implement it, so just capping it at 8 seems like a reasonable fast solution
> cap cpu count of VM created for controller node at 8

- cloudinstall/utils.py
- test/test_utils.py
Adds tests and fixes one issue noticed while writing tests - stderr was not being collected separately in get_command_output()
> add -E to user_sudo command in get_command_output.

- cloudinstall/charms/controller.py
- test/test_charm_controller.py
we now render the network setup script as a template, but multi installs don't have a meaningful 'lxc_network' config-- getopt will return False and fail as in #497 .
This uses a dummy '0' value for multi installs, which is OK because the script doesn't set up networks for multi anyway.
It also adds tests for the changed function in charms/controller.py
> do not attempt to get lxc_network for multi install

- cloudinstall/placement/controller.py
now that the placement code is smarter about determining which charms to place by default, we can re-enable the contrib charms to allow them to be added in the placement UI
> re-enable contrib charms now that placement has CharmState

- cloudinstall/placement/controller.py
- cloudinstall/placement/ui.py
Shows conflicted status of charms.
Here's a screenshot with all required charms placed and no conflicts:
Here's a screenshot where we placed swift, so now ceph-radosgw is blocked due to conflict, and the button is disabled. If you remove swift, ceph-radosgw will be unblocked:
Now here's a screenshot where we placed Ceph-OSD and Swift-Proxy, so now Ceph is required due to a Ceph-OSD->Ceph dep, and swift is required due to swift-proxy->swift dep, so those deps are shown to explain the newly required charms. Also ceph-radosgw is blocked again, that's shown here too:
> Show deps and conflicts in placement ui, disallow placing conflicting charms

- cloudinstall/charms/__init__.py
- cloudinstall/charms/controller.py
- cloudinstall/charms/glance_simplestreams_sync.py
- cloudinstall/charms/keystone.py
- cloudinstall/charms/quantum.py
- cloudinstall/consoleui.py
- cloudinstall/core.py
- cloudinstall/juju.py
- cloudinstall/service.py
- test/test_charms.py
- test/test_core.py
- test/test_ev.py
- test/test_juju_state.py
Refactored how we are waiting for services to start before
relations/post processing are being handled.
Removed the needs to override set_relations() in charms in order
to define additional wait checks as this is handled automatically.
> Wait for services to start

- cloudinstall/core.py
- cloudinstall/placement/controller.py
- cloudinstall/placement/ui/__init__.py
- cloudinstall/placement/ui/machine_widget.py
- cloudinstall/placement/ui/machines_list.py
- cloudinstall/placement/ui/service_chooser.py
- cloudinstall/placement/ui/service_widget.py
- cloudinstall/placement/ui/services_list.py
- test/test_placement_ui.py
Prior to this branch, users had to place a sub charm (e.g. NTP or ceilometer-agent) on a specific machine, even though the deploy code ignored the placement and correctly issued a deploy with no MachineSpec.
Now, the code generates a placeholder machine to hold sub charms, and sub charms just have a button that says 'Add' instead of 'select machine'.
The placeholder machine is displayed differently from other machines (no hardware info is shown), and is at the end of the machine list. Otherwise, clearing some or all of the services off the placeholder works the same as with regular machines.
> Handle subordinate charms correctly in placement UI

- cloudinstall/core.py
- cloudinstall/placement/controller.py
Also adds an exception for failures in add_machine, to surface fatal problems to the user as soon as possible.
> Avoid creating duplicate placeholder for subordinate charms on single

- cloudinstall/gui.py
- cloudinstall/task.py
since PegasusGUI is used in both install and status, but Tasker is only used in install, we should register the toplevel exception dialog box callback in PegasusGUI instead.
> register exception callback in PegasusGUI

- cloudinstall/charms/__init__.py
- cloudinstall/charms/ceilometer.py
- cloudinstall/charms/ceph.py
- cloudinstall/charms/ceph_osd.py
- cloudinstall/charms/cinder.py
- cloudinstall/charms/compute.py
- cloudinstall/charms/controller.py
- cloudinstall/charms/glance.py
- cloudinstall/charms/glance_simplestreams_sync.py
- cloudinstall/charms/heat.py
- cloudinstall/charms/horizon.py
- cloudinstall/charms/jujugui.py
- cloudinstall/charms/keystone.py
- cloudinstall/charms/mongodb.py
- cloudinstall/charms/mysql.py
- cloudinstall/charms/neutron_api.py
- cloudinstall/charms/neutron_openvswitch.py
- cloudinstall/charms/quantum.py
- cloudinstall/charms/rabbitmq.py
- cloudinstall/charms/swift.py
- cloudinstall/charms/swift_proxy.py
- cloudinstall/gui.py
- test/files/charm_plugins/charms/horizon.py
'menuable' hides some charms from showing in the main status screen, but it's not well documented and no one remembers why some are hidden and others aren't.
Subordinate charms are not displayed because they have no units listed in 'juju status'. This does not change that.
In multi installs, this should only affect ceph-radosgw, which will now be displayed if it is deployed.
This doesn't change anything in single installs, because ceph-radosgw is not deployed in single.
> remove menuable

- cloudinstall/charms/__init__.py
- cloudinstall/charms/swift.py
Fixes #505. Swift was not started because relation to swift-storage was not made.
Tested in single-install by checking that 'swift stat' returns something meaningful and that 'swift list' shows the images from glance.
(Note, you need to use something like this to look in swift using the right user account:
`OS_USERNAME=image-stream OS_TENANT_NAME=services OS_PASSWORD=$pass swift list`
where `$pass` is the long hex password that can be found in /etc/glance-simplestreams-sync/identity.yaml on the glance-simplestreams-sync unit.
Also adds logging to help diagnose this in the future.
> Fix swift-storage <-> swift-proxy relation

- bin/openstack-status
- cloudinstall/charms/__init__.py
- cloudinstall/core.py
- cloudinstall/ev.py
- cloudinstall/gui.py
- cloudinstall/placement/controller.py
- cloudinstall/placement/ui/__init__.py
- cloudinstall/placement/ui/add_services_dialog.py
- cloudinstall/placement/ui/machine_widget.py
- cloudinstall/placement/ui/machines_list.py
- cloudinstall/placement/ui/service_chooser.py
- cloudinstall/placement/ui/service_widget.py
- cloudinstall/placement/ui/services_list.py
- cloudinstall/state.py
- test/test_placement_controller.py
- test/test_placement_ui.py
- tools/fast-run-single-status
Many changes.
- placement controller now tracks whether or not a service has been deployed.
- add-unit ui with separate queues replaced by new ui using same core.py deploy infrastructure as initial deploy
- placement UI refactored into several smaller files
- several refactorings for clarity and to remove dead code
NOTE:
tested well with single-install mode. I have not tested it in multi-install. 
@battlemidget: please give it a try on multi.
> Use placement infrastructure for add-services dialog

- cloudinstall/single_install.py
This fixes the issue where the bind mounts were no longer working properly on lxc 1.1+
> make fstab file explicit for lxc 1.1+ templates. Fixes #559.

- cloudinstall/charms/__init__.py
Fixes TypeError when deploying charms with constraints, previously hidden bug because glance-simplestreams-sync does not have constraints.
> fix constraint arg

- cloudinstall/gui.py
regardless of status text length
> tweak status text padding so IPs always line up 

- bin/openstack-install
- cloudinstall/charms/__init__.py
Add support for --next-charms, which pulls the current stable unreleased openstack charms.
> allow using the /next charms from openstack-charmers

- cloudinstall/install.py
using %s and .format() doesn't work, the result was oddly no exception but also no string shown in the title
after fixing that I noticed that the title wrapped across more than one line and looked weird. trying to fix that made urwid burp on smaller screens so I gave up.
My argument for giving up being OK is that although it's nice to have context, it's not totally necessary in the title box there. :shrug: 
I'm open to arguments that we should try harder to fix this...
> Remove install type from password dialog box title

- cloudinstall/placement/ui/__init__.py
- cloudinstall/placement/ui/services_list.py
Fixes #558 and another issue I noticed while tracking that one down (compute was getting hidden after being assigned)
I left the show/hide decision tracing code I used to debug this in, disabled by default as it's very verbose.
You can enable it by setting "trace_updates" to True in the ServicesList constructor.
> Fix display of available services in placement UI

- cloudinstall/core.py
- cloudinstall/gui.py
Cancel worked when it was an overlay and I didn't test it after I made it a full ControllerState.
Needed to make a cancel callback that switched states and redrew.
Works now.
> Make cancel button in add-unit UI actually work

- share/templates/userdata.yaml
Avoids things like trying to resize / using btrfs, which will fail inside a container.
Fixes #586.
> Add resize_rootfs: False to top level container cloud-init userdata.

- bin/openstack-install
- cloudinstall/placement/controller.py
- docs/openstack-config.md
- share/templates/charmconf.yaml
- test/test_placement_controller.py
- test/test_placement_ui.py
Removes --storage, now the only supported way to choose your storage backend is via the add-unit dialog, which can handle the complexity of which required/optional charms you want.
There's one issue - the cinder charmconf template checked this flag and can't do the equivalent once it's gone.
I think I've put in an adequate workaround, but please see my comment here for details: https://github.com/Ubuntu-Solutions-Engineering/openstack-installer/issues/540#issuecomment-102544344
> Remove --storage CLI option. Add-unit dialog should be used instead.

- bin/openstack-install
- cloudinstall/config.py
- cloudinstall/single_install.py
- share/templates/juju-env/single.yaml
- share/templates/userdata.yaml
Allows you to point the installer at an existing apt proxy.
only applies to single installs.
If you have a fast caching proxy, this will use it for the container creation. 
**WIP** It should also use it for the juju-created images but the juju env wasn't right. fixing that now
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/613)
> Add support for specifying an APT caching proxy, for e.g. apt-cacher-ng

- cloudinstall/placement/ui/__init__.py
The default values shown are only true if the installer creates your MAAS for you.
Since that's no longer a well-supported path, the shown values are almost always wrong.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/621)
> Remove misleading username/pass for MAAS

- cloudinstall/utils.py
If config.yaml exists but is empty, yaml.load returns None, which we
try to use to update a dict, which throws an exception, which is
not caught or printed and we bail
this is frustrating because it doesn't print an error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/623)
> Avoid a crash by checking for None from yaml.load

- cloudinstall/charms/__init__.py
- cloudinstall/utils.py
- share/templates/charmconf.yaml
We can't use http urls in openstack-origin-git, so we just point everything at github.com because some firewalls (like canonical's internal) have a special rule allowing git connections to github but denying that port elsewhere.
The better fix would be to simply use http:// for the git urls so they'd go through your proxy, which would work fine except for a bug in charmhelpers: https://launchpad.net/bugs/1472416
We can revisit once that's fixed in charmhelpers
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/633)
> Fix openstack-origin-git from behind a proxy

- share/templates/charmconf.yaml
The charms do in fact do the right thing with http repo urls, so use them so we can go thru the proxy
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/636)
> Use http repo urls so http proxy settings are used.

- cloudinstall/single_install.py
- debian/openstack.modprobe
Attempts to check if the kvm_intel nested param is ON for single
installs, which require nested containers to start any Nova VMs.
If the system has qemu-system-x86 installed, it will probably be ON,
because that package installs a /etc/modprobe.d/qemu-system-x86.conf
file to set it. If not, the default is OFF for kvm_intel. kvm_amd is
default ON.
Adds a modprobe.d/openstack.conf file using dh_installmodules to keep
the setting thru reboots.
Tries to reload the kvm_intel kernel module to pick up the new
modprobe.d settings.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/638)
> Ensure that nested KVM is enabled for single

- cloudinstall/charms/__init__.py
A previous commit removed the local repo to ensure that repeated deploys
will still work even if there was already a downloaded branch. This
restricts that to only remove the charm currently being downloaded, to
allow for later inspection.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/639)
> Keep local charm branches around

- bin/openstack-install
- cloudinstall/controllers/__init__.py
- cloudinstall/controllers/install/__init__.py
- cloudinstall/controllers/install/landscape.py
- cloudinstall/controllers/install/multi.py
- cloudinstall/controllers/install/single.py
- cloudinstall/controllers/installbase.py
- test/test_install.py
- test/test_landscape_install.py
- test/test_multi_install.py
- test/test_state.py
- tox.ini
This is the start of some re-organizing of code. This first bit is to place the actual install section into separated controller directories. Once this is done I will start further separating out what is considered 'controller' code versus 'view' code.
Once the controller/view code are in their respective places I will then tackle the async code to be easier managed and acted upon in case of error rather than relying on our global exec handler.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/652)
> Start of install controller separations

- bin/openstack-status
- cloudinstall/maas/__init__.py
- cloudinstall/placement/controller.py
Passing --maas-tag=foo will make the installer act as if the only
machines in MAAS are the ones with 'foo' as one of their tags.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/668)
> Add --maas-tag to filter machines used

- bin/openstack-config
Users of this utility expect a string with no whitespace, as they often
assign it directly to a shell variable.
Note this solves a weird problem with the simplestreams-sync status listener not being able to get initial status - it tries to get juju_home from openstack-config, and ends up getting "~/.cloud-install/juju\n", which it then uses in a call to 'juju run', and that apparently causes juju to create that directory, which gets displayed in 'ls' as '~/.cloud-install/juju?'
I think it probably also caused some reports of unexpected error messages with the uninstall script in the single install case, where the container_network config var is used to pass to 'route del', and that having a newline in it might cause spurious messages.
Signed-off-by: Mike McCracken …
> openstack-config: write result with no newlines

- bin/openstack-uninstall
This avoids https://bugs.launchpad.net/juju-core/+bug/1490865
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/687)
> check if env is bootstrapped before destroying

- bin/openstack-uninstall
this didn't work if the env *was* bootstrapped
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/688)
> Fix bash thinko

- bin/openstack-install
- cloudinstall/utils.py
- share/templates/charmconf.yaml
In some cases a stable branch isn't available yet, so we can use master instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/690)
> Change --openstack-tip to --openstack-git-branch to allow getting master

- cloudinstall/charms/__init__.py
- cloudinstall/charms/ceilometer.py
- cloudinstall/charms/ceilometer_agent.py
- cloudinstall/charms/ceph.py
- cloudinstall/charms/ceph_osd.py
- cloudinstall/charms/ceph_radosgw.py
- cloudinstall/charms/cinder.py
- cloudinstall/charms/cinder_ceph.py
- cloudinstall/charms/compute.py
- cloudinstall/charms/controller.py
- cloudinstall/charms/glance.py
- cloudinstall/charms/glance_simplestreams_sync.py
- cloudinstall/charms/heat.py
- cloudinstall/charms/horizon.py
- cloudinstall/charms/jujugui.py
- cloudinstall/charms/keystone.py
- cloudinstall/charms/mongodb.py
- cloudinstall/charms/mysql.py
- cloudinstall/charms/neutron.py
- cloudinstall/charms/neutron_api.py
- cloudinstall/charms/neutron_openvswitch.py
- cloudinstall/charms/ntp.py
- cloudinstall/charms/rabbitmq.py
- cloudinstall/charms/swift.py
- cloudinstall/charms/swift_proxy.py
- test/test_charms.py
We needed a way to define charms that are available in
some, all, any of particular branches in order to be made
available depending on the requirements.
For example, currently, the 'tempest' charm is only
available in a /next branch and not in the charmstore.
This feature allows us to be more specific as to what
remote sources are available for said charm.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/694)
> Change have_nextbranch to available_sources

- cloudinstall/controllers/installbase.py
- cloudinstall/core.py
- cloudinstall/ev.py
- cloudinstall/gui.py
- cloudinstall/notify.py
Currently, if an exception occurs we use a popup box
to let the user know that an error happened. However,
in some cases this may be hidden behind the fact that
the update alarms are still running. Meaning, it could
potentionally hide the overlay with another UI event
like updating the progress status view.
The problem this observer solves is it allows us to
call various functions based on the Event() emitted.
This code shows how that is possible when an exception
happens as it will remove the eventloops alarms and
allow the exception error message to stay seen in the
UI.
The other minor thing is the reason why I did this was
because I don't want to stop the eventloop entirely b/c
we'll still need access to keyboard commands, like (q)
in order for the user to quit out of the ui if a …
> Use an observable for handling events

- bin/openstack-install
- bin/openstack-status
- cloudinstall/alarms.py
- cloudinstall/controllers/install/single.py
- cloudinstall/controllers/installbase.py
- cloudinstall/core.py
- cloudinstall/ev.py
- cloudinstall/gui.py
- cloudinstall/notify.py
- cloudinstall/task.py
- cloudinstall/ui/views/error.py
Add support for a new ErrorView detailing where users should report bugs and provides a more readable design when exception happen.
Also added a alarm monitor to keep up with and easily abort all event loop alarms. I think this was one of the problems previously where some errors were being hidden due to the nature of the alarms and having them refresh the UI every so often.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/699)
> Patch use errorview

- cloudinstall/api/container.py
Let exception catchers handle it.
This will make the logs less confusing, since there are usually at least 10 lines with error logs that are really expected failures.
> Don't log an error which may be expected. 

- cloudinstall/core.py
Noticed an issue where we would set current_state to 0
regardless if it was already set in the config.
If the status screen exits then re-running the status
screen should automatically reload from current_state
2 which is the services view
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/703)
> Don't initialize current_state if already set

- bin/openstack-status
- cloudinstall/config.py
- cloudinstall/core.py
- cloudinstall/utils.py
- test/test_config.py
- test/test_core.py
- test/test_ev.py
- test/test_juju_state.py
- test/test_landscape_install.py
- test/test_multi_install.py
- test/test_placement_controller.py
- test/test_placement_ui.py
- test/test_state.py
- test/test_utils.py
Several commits that improve error handling behavior in openstack-status.
Fixes some long-standing annoyances.
Now if there's an error in config.yaml or placements.yaml, the exception message is printed to the screen and the terminal isn't reset because we haven't started the GUI yet.
Also prints a more understandable error message in some cases, in particular for the placements.yaml parsing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/707)
> Status config error sanity

- cloudinstall/controllers/install/single.py
This is the fix for running on wily hosts after the recent cloud image change that preinstalled lxc.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/742)
> Restart lxc-net on wily to pick up our changes

- cloudinstall/charms/glance_simplestreams_sync.py
This re-enables the sync status messages in the status UI.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/753)
> image-sync: re-add sync-rabbit relation

- cloudinstall/ev.py
- cloudinstall/gui.py
We don't use overlays anywhere in the application now. Removing this
code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/756)
> Remove overlay code

- cloudinstall/gui.py
- cloudinstall/ui/views/__init__.py
- cloudinstall/ui/views/machinewait.py
Small organizational change to start moving Views into
their own ui.views namespace
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/758)
> Move machinewaitview into ui.views path

- cloudinstall/charms/glance_simplestreams_sync.py
Includes fix for syncing the same image twice.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/770)
> Bump glance charm to rev 7 to pick up recent fixes

- share/templates/nova-controller-setup.sh
Advice from Rob to switch from nova to using neutron for
security group creation
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/769)
> Use neutron security group cli

- cloudinstall/ui/views/services.py
use '-' instead of 'x'
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/772)
> Tweak container label for bare-metal machines

- cloudinstall/core.py
- cloudinstall/gui.py
Tested on an existing single install using tools/fast-run-single-status. worked for me.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/774)
> services gui: Update phase status every refresh.

- cloudinstall/service.py
- cloudinstall/ui/views/services.py
Shows AgentState and WorkloadInfo, which show as AGENT-STATE and MESSAGE
in juju status --format=tabular.
Does not use WorkloadState, which is not well supported in current
charms and mostly just says 'unknown'.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/778)
> status: Use extended info from juju if available

- cloudinstall/juju.py
Fixes crash in display when machine can not be created for a unit, or is
not ready yet.
When a machine can't be found, the default machine id of -1 is returned,
which is eventually passed as-is to a Text() constructor, which fails.
Nothing other than display and comparisons uses this value, so it's ok
to use something arbitrary as long as it's not something juju would
actually assign to a machine.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/779)
> Use string for missing juju machine id

- cloudinstall/core.py
needed to pass a callable, not the result of submitting to the pool
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/780)
> add services ui: fix traceback in deploy

- test/test_utils.py
if worker_multiplier is not defined, the glance dict should be None, so
let's test that explicitly
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/784)
> test_multiplier: Test expected value in both cases

- cloudinstall/core.py
- cloudinstall/gui.py
- cloudinstall/task.py
- cloudinstall/ui/views/__init__.py
- cloudinstall/ui/views/nodeinstallwait.py
Cleanup to only redraw the elapsed seconds and KITT bar during
alarm's. Also show whole seconds rather than a float.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/783)
> Rework node install wait view to not redraw entire screen

- cloudinstall/charms/__init__.py
If we fail to deploy a charm raise an exception as this should
never happen.
Fixes #791
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/792)
> Raise exception on failed deploy

- bin/openstack-install
- cloudinstall/gui.py
If urwid is unable to determine proper encoding we fail before
reaching the ui.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/790)
> catch encoding problems earlier

- cloudinstall/async.py
- cloudinstall/charms/__init__.py
- cloudinstall/core.py
- cloudinstall/ev.py
- cloudinstall/gui.py
- test/test_core.py
Shutdown was hanging after the urwid loop stopped, due to threads in the
thread pool looping forever, or just for a long time.
Async launched threads need to occasionally check if they need to kill
themselves.
Added async.shutdown to cleanly shutdown the executor and signal an
event that the threads check occasionally.
Added async.sleep_until to provide a sleep() workalike that checks every
.1 seconds for the shutdown Event and raises an exception if it is set.
Occasionally this is used with a timeout of 0 to just check for the
event once.
These changes should quit cleanly within a minimum of time - although
sometimes it will still stall while waiting for e.g. a remote execution
of a post-processing script, as the checks are only inline.
[<img src="https://reviewable.io/review_button.png" …
> Fix hanging on quit

- cloudinstall/consoleui.py
Avoids spurious error message in landscape headless installs, that look like this:
```
[INFO: 01-14 23:46:34] Running
[INFO: 01-14 23:46:44] Downloading latest Landscape Autopilot bundle
[INFO: 01-14 23:46:44] Deploying Landscape
[INFO: 01-14 23:56:01] Registering against Landscape
...
[INFO: 01-14 23:56:04] Missing ConsoleUI() attribute: clear_status
etc ...
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/824)
> consoleui: add clear_status dummy

- share/templates/charmconf.yaml
The cloud-installer/simplestreams-testing PPA has a copy of
simplestreams for trusty that includes the progress reporting code we
need. It had been installed unconditionally by the GSS charm but as that
charm is now in use by others, that has caused problems.
Instead we have added a 'source' config option in this MP:
https://code.launchpad.net/~mikemc/charms/trusty/glance-simplestreams-sync/add-source-config/+merge/282806
this allows us to just set it here and others will not use it by default.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/826)
> Add 'source' option to glance-simplestreams-sync

- cloudinstall/placement/controller.py
refresh unassigned_services before checking if any services are
unassigned after performing auto assignment
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/827)
> fix bug in autoplacement

- share/templates/charmconf.yaml
This reverts commit 6beb57c37f1babad12463c639fc6aad7d11c6cdf.
We need to wait until the charm is updated to commit this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/830)
> Revert "Add 'source' option to glance-simplestreams-sync"

- cloudinstall/placement/ui/__init__.py
'no machines' MAAS ui will not be shown, even when there really aren't
any, because we've added the juju default placeholder.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/831)
> fix no machines UI

- cloudinstall/api/container.py
- cloudinstall/controllers/install/single.py
Required because of recent changes to LXD that no longer include LXC's default device configuration.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/838)
> LXD toplevel container: Add /dev/net/tun and /dev/kvm as devices

- cloudinstall/charms/ceilometer.py
- cloudinstall/charms/ceilometer_agent.py
- cloudinstall/charms/ceph.py
- cloudinstall/charms/ceph_radosgw.py
- cloudinstall/charms/cinder.py
- cloudinstall/charms/cinder_ceph.py
- cloudinstall/charms/compute.py
- cloudinstall/charms/controller.py
- cloudinstall/charms/glance.py
- cloudinstall/charms/glance_simplestreams_sync.py
- cloudinstall/charms/heat.py
- cloudinstall/charms/horizon.py
- cloudinstall/charms/jujugui.py
- cloudinstall/charms/keystone.py
- cloudinstall/charms/mongodb.py
- cloudinstall/charms/mysql.py
- cloudinstall/charms/neutron.py
- cloudinstall/charms/neutron_api.py
- cloudinstall/charms/neutron_openvswitch.py
- cloudinstall/charms/rabbitmq.py
- cloudinstall/charms/swift.py
- cloudinstall/charms/swift_proxy.py
Mainly affects openstack charms, for whom charmhelpers breaks with new
openstack packages from today, unless updated.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ubuntu-solutions-engineering/openstack-installer/842)
> Bump all pinned charms to latest.
